# Created with assistance from Claude AI (Anthropic)
# Date: 2025-05-18
version: "3.8"

services:
  # Stack Auth server (combines API backend and Dashboard)
  stack-auth:
    image: stackauth/server:latest
    ports:
      - "8101:8101" # Dashboard UI
      - "8102:8102" # API Backend
    environment:
      # Core URLs
      - NEXT_PUBLIC_STACK_API_URL=${NEXT_PUBLIC_STACK_API_URL}
      - NEXT_PUBLIC_STACK_DASHBOARD_URL=${NEXT_PUBLIC_STACK_DASHBOARD_URL}

      # Database connection
      - STACK_DATABASE_CONNECTION_STRING=${DATABASE_URL}
      - STACK_DIRECT_DATABASE_CONNECTION_STRING=${DATABASE_URL}

      # Server secret for JWT encryption
      - STACK_SERVER_SECRET=${STACK_SECRET_SERVER_KEY}

      # Seed script settings
      - STACK_SEED_INTERNAL_PROJECT_SIGN_UP_ENABLED=${STACK_SEED_INTERNAL_PROJECT_SIGN_UP_ENABLED}
      - STACK_SEED_INTERNAL_PROJECT_OTP_ENABLED=${STACK_SEED_INTERNAL_PROJECT_OTP_ENABLED}
      - STACK_SEED_INTERNAL_PROJECT_ALLOW_LOCALHOST=${STACK_SEED_INTERNAL_PROJECT_ALLOW_LOCALHOST}
      - STACK_SEED_INTERNAL_PROJECT_USER_EMAIL=${STACK_SEED_INTERNAL_PROJECT_USER_EMAIL}
      - STACK_SEED_INTERNAL_PROJECT_USER_PASSWORD=${STACK_SEED_INTERNAL_PROJECT_USER_PASSWORD}
      - STACK_SEED_INTERNAL_PROJECT_USER_INTERNAL_ACCESS=${STACK_SEED_INTERNAL_PROJECT_USER_INTERNAL_ACCESS}

      # Email settings
      - STACK_EMAIL_HOST=${SMTP_HOST}
      - STACK_EMAIL_PORT=${SMTP_PORT}
      - STACK_EMAIL_USERNAME=${SMTP_USER}
      - STACK_EMAIL_PASSWORD=${SMTP_PASSWORD}
      - STACK_EMAIL_SENDER=${SMTP_FROM_EMAIL}
      - STACK_EMAIL_SENDER_NAME=${SMTP_FROM_NAME}

      # Svix webhooks configuration
      - STACK_SVIX_SERVER_URL=${STACK_SVIX_SERVER_URL}
      - NEXT_PUBLIC_STACK_SVIX_SERVER_URL=${NEXT_PUBLIC_STACK_SVIX_SERVER_URL}
      - STACK_SVIX_API_KEY=${STACK_SVIX_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      inbucket:
        condition: service_started
      svix:
        condition: service_started
    networks:
      - default
    profiles:
      - ${STACK_ENV:-dev}
      - prod

  # PostgreSQL database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: stack_auth
      POSTGRES_PASSWORD: stack_auth_password
      POSTGRES_DB: stack_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stack_auth"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

  # Inbucket for email testing (development only)
  inbucket:
    image: inbucket/inbucket:stable
    ports:
      - "8105:9000" # Web interface
      - "2500:2500" # SMTP
    environment:
      - INBUCKET_MAILBOXNAMING=full
    networks:
      - default
    profiles:
      - ${STACK_ENV:-dev}

  # Svix for webhooks
  svix:
    image: svix/svix-server:latest
    ports:
      - "8071:8071" # Svix API
    environment:
      - SVIX_JWT_SECRET=${SVIX_JWT_SECRET}
      - SVIX_DB_DSN=postgres://stack_auth:stack_auth_password@postgres:5432/svix
    volumes:
      - svix_data:/data
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
    profiles:
      - ${STACK_ENV:-dev}
      - prod

networks:
  default:
    name: stack-auth-network

volumes:
  postgres_data:
  svix_data:
